### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by WesSec** [formcore/x265-videoconverter#1]
First of all. thanks for sharing the code, awesome idea.

when i run 
```
python3 main.py -s
```
the program returns
```
FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe -v quiet -print_format json -show_format -show_streams "/mnt/storage/movies/Madagascar 3 Europe\'s Most Wanted (2012)/Madagascar 3 Europe\'s Most Wanted (2012) Bluray-1080p.mkv"': 'ffprobe -v quiet -print_format json -show_format -show_streams "/mnt/storage/movies/Madagascar 3 Europe\'s Most Wanted (2012)/Madagascar 3 Europe\'s Most Wanted (2012) Bluray-1080p.mkv"'
```

when i probe the file manually with ffprobe it works, but it seems like the script has some trouble with escaping quotation marks or spaces.

I hope you can help me :)

**Comment by samule-i** [comment]
It should work reasonably well with spaces, as I've had no issues there, I will try to recreate the problem and see if I can't find where it's choking.

Could be because this is linux, as I've only tested on windows.

**Comment by samule-i** [comment]
@wessel145 , I was able to re-create the issue using linux, Because they were handling paths differently there was a problem for Linux finding paths as they were handled. I've tested out a patch and I was able to perform a scan and conversion on a file that closely mimics the one that was giving you an issue... if you could report back if/when you test the new master and get back to me so I know to close this issue.

**Comment by WesSec** [comment]
Can confirm scanning works now. awesome, thanks!
